name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup yarn
        run: npm install -g yarn

      - name: setup node with yarn caching
        uses: actions/checkout@v2
        with:
          node-version: "14"
          cache: yarn

      - run: yarn

      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
